### ISSUE TITLE
GEFS Forecast data

### ISSUE THREAD

**Issue by potterzot** [ropensci/rnoaa#105]
I have implemented fetching of GEFS forecast data in netCDF, and it seems like it would maybe be useful to incorporate that into rnoaa? I'd be happy to do some work on that if necessary. I have a gist with the initial example [here](https://gist.github.com/potterzot/308f39a5d4a64c37ffb0).

We're working on some agriculture decision tools that incorporate both historical and forecast climate data, and as much as possible I'd like to incorporate that work into rnoaa so that others can access that data more easily.

**Comment by sckott** [comment]
hi @potterzot - back from vacation now. 

Sounds great. Can you submit a pull request?

**Comment by sckott** [comment]
@potterzot getting to that PR soon?

**Comment by potterzot** [comment]
Hi @sckott - The PR was done a while ago in this [issue](https://github.com/ropensci/rnoaa/pull/106#issuecomment-138993955), I think I created a second issue to make the PR, so I'll close this one now.

**Comment by sckott** [comment]
ah, okay
