### ISSUE TITLE
nldn dataset - "Error in UseMethod("xpathApply")"

### ISSUE THREAD

**Issue by selu220** [ropensci/rnoaa#107]
When I attempt to employ a simple example

`swdi(dataset='nldn', startdate='20140101', enddate='20140102', bbox = c(-91, 30, -90, 31))`

I get the following error:

```r
Error in UseMethod("xpathApply") : 
  no applicable method for 'xpathApply' applied to an object of class "raw"
```

Other data sets seem to work fine.

**Comment by sckott** [comment]
I'll take a look

**Comment by sckott** [comment]
@selu220 available to government and military users only https://www.ncdc.noaa.gov/data-access/severe-weather/lightning-products-and-services 

I guess I'll make a note that it's only avail. to certain users

**Comment by sckott** [comment]
thought it should fail better for users that dont have access, will do that

**Comment by sckott** [comment]
thanks @selu220

**Comment by selu220** [comment]
thank you!
