### ISSUE TITLE
Some GHCND urls fail occassionally

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#110]
Build in a retry maybe, try perhaps 2 or 3 times, then fail more gracefully than 

```r
 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer 
```

**Comment by jread-usgs** [comment]
@sckott just noticing that you don't use `times` for your retry. Can this get stuck in a loop? https://github.com/ropensci/rnoaa/blob/67ac0eeda4ae7fa566f75500915ce25f516a53ea/R/ghcnd.R#L215

**Comment by sckott** [comment]
thanks - will have a look

**Comment by sckott** [comment]
@jread-usgs using `times` now :)  thanks for reminding me.

**Comment by jread-usgs** [comment]
:+1:
