### ISSUE TITLE
Add support for CO-OPS (Tides and Currents) API

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rnoaa#111]
See http://co-ops.nos.noaa.gov/api/

**Comment by sckott** [comment]
cool, thanks @fmichonneau for doing

**Comment by sckott** [comment]
Closing for now, initial implementation in, can open new issues as needed for these functions

**Comment by fmichonneau** [comment]
Thanks @jsta and @sckott! I'll check it out soon.

**Comment by sckott** [comment]
great, thanks @fmichonneau

**Comment by jsta** [comment]
@fmichonneau @sckott #129 adds some more examples that might help you test
