### ISSUE TITLE
change ncdf to ncdf4

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#117]
message from Ripley:

> which depend on package ncdf.  The latter is now deprecated and
scheduled to be removed from CRAN in Jan 2016.  It has only been keep
this long because ncdf4 was not available for Windows: it now is (on
CRAN extras, a default repository for binary installs).  Please convert your package to use either ncdf4 or RNetCDF as soon as possible and definitely by early January.  (For the second group this
could just mean removing references to ncdf as the package passes its
checks without it.)

**Comment by sckott** [comment]
https://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.2/

**Comment by sckott** [comment]
checked on a windows vm box, and does indeed install from that cran repo

**Comment by sckott** [comment]
@potterzot `ncdf4` now has windows binaries, so we'll switch to that. I already switched out `ncdf` for `ncdf4` in the buoy functions. I can do for gefs or you can if you like. Let me know which.

**Comment by potterzot** [comment]
I'll take care of it, since I'm looking at #119 also.

**Comment by sckott** [comment]
@potterzot for reference, here's the changes I did for `ncdf4` for the buoy functions   https://github.com/ropensci/rnoaa/blob/master/R/buoy.R#L130-L161
