### ISSUE TITLE
Character buoy ids

### ISSUE THREAD

**Issue by jsta** [ropensci/rnoaa#118]
I cannot seem to retrieve any data associated with buoys that have character ids. For example, 

` buoy(dataset = "stdmet", buoyid = "VCAF1")`

returns

> Error: length(url) == 1is not TRUE

See [http://www.ndbc.noaa.gov/to_station.shtml](http://www.ndbc.noaa.gov/to_station.shtml)

**Comment by sckott** [comment]
woops, i only accounted for numeric buoy ids, fixing

**Comment by sckott** [comment]
@jsta reinstall from github, and try again, shoudl be fixed
