### ISSUE TITLE
URL for gefs data python code broken

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#121]
http://sila.cee.wsu.edu/forecasts/WeatherAndClimateDatafromNWS.html

@potterzot 

is the code somewhere else you could point to?

**Comment by potterzot** [comment]
Hi Scott - it appears that the link is down and I haven't gotten a
response. The change you made is great though. Thanks!

---------------------
Nicholas Potter
http://potterzot.com

**Comment by sckott** [comment]
okay, hopefully they'll respond, i'll leave it open for a while in case you get a response soon

**Comment by sckott** [comment]
no response, just leaving as is

**Comment by potterzot** [comment]
Just FYI I did have a conversation with Von Walden, the author of the python code, and he said that the link is currently down, he's not that concerned about it, and he will let me know if/when it becomes available again.

**Comment by sckott** [comment]
okay, thanks. Anywhere else the code lived? on bitbucket/github/gitlab/anywhere?

p.s., did I already ask you this? Why are `gefs_GET()` and `gefs_CONNECT()` exported?  seems like you don't lay out any examples for those, suggesting maybe they aren't meant to be used by users?

**Comment by potterzot** [comment]
I don't think the code is available anywhere at the moment. He had it on his laptop, threw it on his site for me to work from, and then took it down again.

re: gefs_GET() and gefs_CONNECT(), I wasn't sure whether they should be exported or not. They are base functions not really meant to be used by users, so maybe I should remove them. I guess I was thinking that I still wanted someone to be able to use them if they really wanted to, but maybe that doesn't really make sense.

**Comment by sckott** [comment]
They just look like internal fxns to me at least, but your more familiar with them.  

By the way, any thoughts on this #127
