### ISSUE TITLE
coops changes

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#126]
@jsta can we change some things

* change numeric data to numeric class. right now, i think all columns numbers, but given back as character
* ...

**Comment by jsta** [comment]
The idea would be to convert character results to numeric? I'll go through the various product results and see how the numeric columns lineup.

**Comment by jsta** [comment]
Also, I see that calls to water level products should throw an error if a datum is not supplied. Currently there is just a silent "no data" return.

**Comment by sckott** [comment]
> The idea would be to convert character results to numeric?  

yes

**Comment by jsta** [comment]
another issue is that the datums and predictions product return a data.frame not named "data"

**Comment by jsta** [comment]
Not all of the data columns are numeric for all products. For example, all of the products except for `monthly_mean` return a character POSIXct date-stamp as the first column.

**Comment by sckott** [comment]
thanks, closing
