### ISSUE TITLE
Problem with ncdf4 where on windows machines doesn't work

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#127]
at least for `gefs` fxns I get an error that the file type can not be read, the `.grib` file type, see if this can be fixed

**Comment by potterzot** [comment]
I'm a little confused on this, is it specific to windows and to gefs? Can you give me a reproducible example to work from?

**Comment by sckott** [comment]
Sure, I'll try it again on windows and paste in the error I get

**Comment by sckott** [comment]
@potterzot e.g, 

```r
lat <- 46.28125
lon <- -116.2188
gefs("Temperature_height_above_ground_ens", lat, lon, date = format(as.Date(Sys.time()) - 1, "%Y%m%d"), forecast_time = "1800", ens_idx=2:4, time_idx=1:8)
```

```
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(gefs_url):
    Error in nc_open trying to open file http://thredds.ucar.edu/thredds/dodsc/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20160120_1800.grbi2
```

**Comment by sckott** [comment]
That `grib2` file format is causing problems, never heard of that format, not sure where to look for solution

**Comment by potterzot** [comment]
some climate data is stored in it. I'll look at it, should be able to fix
quickly. Thanks for bringing it to my attention and thanks for the example!

---------------------
Nicholas Potter
http://potterzot.com

**Comment by sckott** [comment]
@potterzot let me know when you get a fix for this, hoping to get the next patch version https://github.com/ropensci/rnoaa/milestones/v0.5.2 pushed soon

**Comment by potterzot** [comment]
@sckott Strange, it works fine on linux. I hope to make it happen this weekend, and push an update in the next couple of days. Will that work?

**Comment by sckott** [comment]
Sounds good

**Comment by potterzot** [comment]
I think this is an upstream bug. Bypassing **rnoaa** and using **ncdf4** directly, I have no problem on linux but can't access the file on windows.

On Linux:
``` r
library(ncdf4)
gefs_url <- "http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20160120_1800.grib2"

con <- nc_open(gefs_url)
vars <- names(con$var)
vars[1:5]
#> [1] "reftime"                          "LatLon_Projection"               
#> [3] "time_bounds"                      "pressure_difference_layer_bounds"
#> [5] "depth_below_surface_layer_bounds"
```

On Windows:
``` r
...
con <- nc_open(gefs_url)
Error in R_nc4_open: NetCDF: Unknown file format
Error in nc_open(t_url) : 
  Error in nc_open trying to open file http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20160120_1800.grib2
```

If this makes sense, I'll submit a bug to ncdf4. 

What would you like to do with the gefs code in the meantime? I can put a notice in that says it doesn't work for windows, or if you would prefer something else just let me know.

**Comment by sckott** [comment]
thanks for looking in to this :+1: 

how about we just stop on windows, for all applicable gefs functions, e .,g, put this code in 

`if (is_windows()) stop("gefs not implemented on windows yet", .call = FALSE)`

**Comment by sckott** [comment]
temporary fix in #133 , closing this, will open new issue to remind us to fix this

**Comment by mauritzvdworm** [comment]
Any update in getting the gefs data using a windows machine?

**Comment by sckott** [comment]
@mauritzvdworm  I don't think so , follow https://github.com/ropensci/rnoaa/issues/134 for updates on this issue
