### ISSUE TITLE
fix gefs on windows at some point

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#134]
in #127 talked about gefs functions failing on windows b/c of unreadable file format - figure out a fix at some point... perhaps a fix can be made to `ncdf4`

cc @potterzot

**Comment by potterzot** [comment]
I did exchange a few emails with the ncdf4 developer. He's of the opinion that the error is not in ncdf4. I haven't had a chance to look into this further but it's on my list for cleanup things to do this summer.

**Comment by sckott** [comment]
thanks for update @potterzot !

**Comment by Wisconsin786** [comment]
I just wanted to check again if someone fixed the this issue on windows. i am getting following error


download.NOAA_GEFS(outfolder="Working/results", lat.in= 45.805925, lon.in = -90.07961, sitename="US-WCr")

Error in ncdf4::nc_open(gefs_url) : 
  Error in nc_open trying to open file http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20190802_1200.grib2

**Comment by sckott** [comment]
thanks @Wisconsin786 - but that fxn is not in this pkg - I see https://pecanproject.github.io/modules/data.atmosphere/docs/reference/download.NOAA_GEFS.html 

with regard to the gefs functionality in this pkg, no, we have not figured it out on windows sadly

**Comment by sckott** [comment]
@potterzot any progress for windows?

**Comment by potterzot** [comment]
@Wisconsin786 @sckott, I wasn't able to verify the `pecan` error because I ran into some installation problems with that package. As far as `rnoaa::gefs()`, I do have access to a Windows machine through VM now, but I probably won't get the chance to revisit this for a couple of months. I've added it to my list to take a look at though.

**Comment by sckott** [comment]
thanks @potterzot - seems like egs for `gefs()` in the pkg no longer work either, e.g., the url generated for the eg in the docs http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/GEFS_Global_1p0deg_Ensemble_20190804_1800.grib2 gives a 404

**Comment by sckott** [comment]
it may be a shot in the dark, but @mdsumner any ideas on gefs on windows? boils down I think to these `.grib2` files not being handled by `ncdf4` - there's wgrib2 cli tool, but last I checked it didn't compile on windows, and I'd rather avoid shelling out

**Comment by potterzot** [comment]
@sckott I think this is an issue with timing, but should still be addressed. I can't reproduce the 404 error using the example docs. If I run the example code

```r
date <- format(as.Date(Sys.time()) - 1, "%Y%m%d")
var <- "Temperature_height_above_ground_ens"
gefs(var, lat, lon, date = date, forecast_time = "1800", ens_idx=2:4,
  time_idx=1:8)
```
It works without an issue. Can you give me a reprex?

**Comment by sckott** [comment]
ah sorry it's been a while. I was trying to construct a url from the function internals, and going to the URL for the grib file for that request gives 

```
Error {
    code = 400;
    message = "Unrecognized request";
};
```

but i guess works with `ncdf4::nc_open`

**Comment by sckott** [comment]
i think it's fine that it just doesn't work on windows since there's so much else to do - sorry windows people
