### ISSUE TITLE
bug found when using rnoaa isd function

### ISSUE THREAD

**Issue by GuodongZhu** [ropensci/rnoaa#136]
I think I found a bug when I use rnoaa isd function. 

A station is uniquely determined by two parameters usaf and wban. 

If we search the station using usaf="702700", wban="00489", the isd.search function will tell us that such station doesn't exist. If we try to grab data using identifiers usaf="702700", wban="00489", we can still get the data. However, the date is discontinuous, e.g., 20140114, 20140115, 20140130.

If we search the station using usaf="702700", wban="489", the isd.search function will tell us that such station exists. However, if we try to grab data using identifiers usaf="702700", wban="489", there is a warning  "do not know how to convert 'w$date' to class “Date”".

**Comment by sckott** [comment]
@GuodongZhu thanks for the report. I'll have a look and report back

**Comment by sckott** [comment]
@GuodongZhu try again after re-installing `devtools::install_github("ropensci/rnoaa")`

**Comment by sckott** [comment]
the station data from `isd_stations()` was reading in the wban field as numeric, and that data can have leading zeros, which are of course stripped off when read in to R. Now that column is read in as character class

also, `isd()` fails better now when the user supplied query doesn't match a real data file

```r
isd(usaf = "702700", wban = "489", year = 2014)
#> Error: download failed for
#>   ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/702700-489-2014.gz 
```

**Comment by GuodongZhu** [comment]
It works now. Thanks sckott ! 

Another question that puzzles me is that the data downloaded from this station (usaf = "702700", wban = "489")  have discontinuous dates. It starts Jan 14 (not Jan 1) and jumps to Jan 21. I have tested some stations, and only this station which is located in Alaska has the problem. Is it because the raw data is recorded this way ?

**Comment by sckott** [comment]
I don't know anything about the date coverage for these data. You could try looking at the  https://www.ncdc.noaa.gov/isd  page and maybe contacting someone that works there

**Comment by GuodongZhu** [comment]
I will try to contact them. Thanks sckott !
