### ISSUE TITLE
ISD data attributes.

### ISSUE THREAD

**Issue by zxy1219** [ropensci/rnoaa#142]

**Comment by zxy1219** [comment]
Hi, why the rnoaa download different attributes from the ISD (Integrated Surface Database) from using the NOAA search tool or ftp?
For example, the rnoaa downloaded data don't include SLP which was introduced in the NOAA's metadata (http://www.ncdc.noaa.gov/cdohtml/3505doc.txt). In stead, they have the "air pressure".

Any one know the reason?

**Comment by sckott** [comment]
can you give an example request with an `rnoaa` function?

**Comment by zxy1219** [comment]
Yes. I use the isd(). Here is my code:
res<- isd(usaf="723630", wban="23047", year=2008, path = "...", overwrite = TRUE)

**Comment by sckott** [comment]
what version of R and `rnoaa` are you using?

**Comment by zxy1219** [comment]
I'm using R 3.2.4, The rnoaa package was installed 3 days ago. It is the 0.5.2?

**Comment by zxy1219** [comment]
I just found that most downloaded data have more than 24 observations per day. Is it not the hourly data?

**Comment by sckott** [comment]
hmm, looks like the slp data is there in the downloaded data, so I may need to edit the parsing code

**Comment by zxy1219** [comment]
Thanks. Just one little suggestion, can you name the attributes in the same way with NOAA's?
This link can provide reference:http://www.ncdc.noaa.gov/cdohtml/3505doc.txt

**Comment by sckott** [comment]
This is the document that matches the data downloaded by the `isd()` function ftp://ftp.ncdc.noaa.gov/pub/data/noaa/ish-format-document.pdf The document you link to http://www.ncdc.noaa.gov/cdohtml/3505doc.txt doesn't seem to match up - What is the context for the http://www.ncdc.noaa.gov/cdohtml/3505doc.txt page? That is, what dataset is it supposed to describe?

**Comment by sckott** [comment]
e.g., your document states that he WBAN identifier is at positions `08-12`, while the pdf I link to states it is positions `11-15`

**Comment by zxy1219** [comment]
I think I figured it out. The data sample provided by NOAA is the "simplified" version, while rnoaa download the "advanced" version. Both of the two version could be extracted by using NOAA's "search tool".

Great thanks!

**Comment by sckott** [comment]
Okay. Which format do you prefer, the simple or advanced format?

**Comment by zxy1219** [comment]
We use the simple version in the past studies. The advanced version looks
fine since they can match with the simple version. Are you going to develop
a function to download the simple version?

On Mon, Mar 21, 2016 at 7:04 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
I wasn't planning to, but we could think about doing that. Are the simple version files avail. via FTP?

**Comment by sckott** [comment]
@zxy1219 any thoughts on my last comment?

**Comment by zxy1219** [comment]
The simple version will be helpful. But the advanced version is good enough for my current project. Thanks a lot.

**Comment by sckott** [comment]
Okay, i'll give the simple version a shot some time, but not a priority for now

**Comment by sckott** [comment]
opened issue for the simple data format, so it doesn't get forgotten here

**Comment by sckott** [comment]
closing this since we have #175 open
