### ISSUE TITLE
Unable to unpack .gz file for some isd stations

### ISSUE THREAD

**Issue by GuodongZhu** [ropensci/rnoaa#145]
When I use isd function 

`isd(usaf="999999", wban="94074",  year =2013, path="")`

I got the following error message

```f
Error in data.frame(normal, proc_other(other), stringsAsFactors = FALSE) : 
 arguments imply differing number of rows: 1, 0 
```

I use Windows and the newest RStudio version.

**Comment by sckott** [comment]
related to #146 i think, that is, internals of `isd()` need to be faster

**Comment by sckott** [comment]
@GuodongZhu the error message you received i believe is because `path=""` is not valid, if you meant the current directory, do `"."` with a dot.

trying  your example to a proper directly though made me realize that we need to speed up the parsing, working on that now

**Comment by GuodongZhu** [comment]
Sorry for the confusion. I has  assigned the path with correct value, I just omitted the value when I pasted here... I still got the same error when I used the default path.

**Comment by sckott** [comment]
Hmm, I don't get that error that you get, I just made some changes to speed up parsing the data, can you reinstall, like `devtools::install_github("ropensci/rnoaa")` and try again

**Comment by GuodongZhu** [comment]
It's a little weird. I reinstalled the package. Now the error message is gone...

Anyway, thank you sckott !
