### ISSUE TITLE
ghcnd_splitvars Broken with `dplyr` v0.5.0

### ISSUE THREAD

**Issue by lawinslow** [ropensci/rnoaa#156]
After upgrading dplyr to v0.5.0 (current CRAN version), the `rnoaa::ghcnd_splitvars` function no longer works. 
```R
> minoc = ghcnd_splitvars(ghcnd('USC00475516'))
Error in is.string(match) : argument "match" is missing, with no default
```
Seems to fail right away on [this select statement](https://github.com/ropensci/rnoaa/blob/master/R/ghcnd.R#L131).

Downgraded to `dplyr` v0.4.3 and it works fine.

**Comment by lawinslow** [comment]
Small world @sckott. Thanks for the noaa package.

**Comment by sckott** [comment]
thanks @lawinslow - sorry about that - i knew a new version was coming, should have caught it, will push a change soon

**Comment by lawinslow** [comment]
np, just thought you'd like to know.

**Comment by sckott** [comment]
@lawinslow try again after reinstall

**Comment by lawinslow** [comment]
Great. Fixed. Thanks!
