### ISSUE TITLE
Imputation of missing weather parameters

### ISSUE THREAD

**Issue by lukas-rokka** [ropensci/rnoaa#158]
enchantment/new feature request: 

It would be very useful with a missing values imputation feature. Personally I'm mostly interested in the ISD dataset, but this should be useful for other NOAA datasets as well.  For many stations and weather parameters it should be possible to use data from nearby stations and do the imputation with existing R-packages (e.g. MICE, hmisc::aregImpute()). For shorter gaps (<3 hours?) interpolation should work fine.

But there are some domain specific issues. E.g. temperature is probably strongly correlated to a nearby stations, while precipitation can vary quite much spatially. Sometimes a new stations replaces an old stations, in these situations the datasets could be simple merged. In other cases two relatively nearby stations can have very different climate (e.g. in Switzerland where two nearby stations could have a mountain peak between them).

**Comment by sckott** [comment]
@lukas-rokka thanks for this. 

`enchantment` I like it 😏 

Want to send a pull request to get started? and we can discuss from there

**Comment by lukas-rokka** [comment]
haha, enchant code would definitely be an enhancement.

I'll not work on it before the next month or so, I let you know when I get something useful done.

**Comment by sckott** [comment]
@lukas-rokka  any thoughts on this?

**Comment by lukas-rokka** [comment]
I don't have time work on this issue in any near future. You can close it, @sckott. 

I've started using reanalysis data instead of station observation data, and then missing data is already handled.

**Comment by sckott** [comment]
thansk @lukas-rokka - okay, will close
