### ISSUE TITLE
expose a function to let users read ISD .gz files w/o using isd() itself

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#169]
from #168

**Comment by sckott** [comment]
@rjbehnke reinstall `devtools::install_github("ropensci/rnoaa")` - added `isd_read()` function, try it and let me know what you think

**Comment by rjbehnke** [comment]
[ISD_Read_Errors.docx](https://github.com/ropensci/rnoaa/files/505038/ISD_Read_Errors.docx)

Scott,  

   Here's the document that describes the errors, etc.  

Ruben

**Comment by sckott** [comment]
thanks @rjbehnke , that is helpful

**Comment by sckott** [comment]
@rjbehnke  woops, your comment belonged in #168 , not here, no worries, just noting this for my own benefit to keep track of things
