### ISSUE TITLE
Integrated surface - hourly (ISH) data access

### ISSUE THREAD

**Issue by Fasle** [ropensci/rnoaa#174]
Hi all, 

I need global hourly weather data and I've been using the NOAA ISH data. I wanted to try to use your library, but I saw that you moved support for the legacy API to /[ignore](https://github.com/ropensci/rnoaa/commit/c10e3763d7feb3d811c2dad11231c189c7f4b283). Can I somehow still use the old API through your library or would I have to fork it and put support for the old API back in manually? Could rnoaa support both versions? 

I cannot find global hourly data that is available through the V2 API. Am I missing something?

Thanks for your help.

**Comment by sckott** [comment]
thanks for your question @Fasle !

That legacy NOAA API was very flaky, often failing. So it didn't seem worth supporting here. You can of course play with that code any way you like. 

have you seen the `isd()` function in `rnoaa`? It does have hourly data within each date. Is that the data you're looking for?  If you point out some example data you can get on NOAA's site e.g., I can see if we can currently get that, or if we'd need to add something

**Comment by sckott** [comment]
closing inactivity
