### ISSUE TITLE
ISD Precipitation data missing

### ISSUE THREAD

**Issue by mrubayet** [ropensci/rnoaa#176]
I don't think isd() can retrieve  precipitation data. I guess you have missed the additional data described in:
ftp://ftp.ncdc.noaa.gov/pub/data/noaa/ish-format-document.pdf. isd() retrieves only mandatory section  however precipitation falls in the additional part of the data set.

**Comment by sckott** [comment]
thanks @mrubuayet 

i did indeed miss some data. i got some of the additional data, but not all. I'm working on that. 

also, breaking off the ISD parser to a new pkg https://github.com/ropenscilabs/isdparser (so users don't need some of the heavier deps of `rnoaa`) - `rnoaa` will use it once on cran

**Comment by mrubuayet** [comment]
Great. Also please check the unit of precipitation in rnoaa documentation for meteo_tidy_ghcnd (). The unit isn't consistent for  input var and the value. I think the output precipitation should be also in tenths of millimeters. Thanks

**Comment by sckott** [comment]
> Also please check the unit of precipitation in rnoaa documentation for meteo_tidy_ghcnd (). The unit isn't consistent for input var and the value. I think the output precipitation should be also in tenths of millimeters

Please open a new issue for this since that deals with ghcnd data

**Comment by sckott** [comment]
closing, should be all fixed now
