### ISSUE TITLE
NOAA API V2 moved to HTTPS since noon today, breaking all(?) api access functions

### ISSUE THREAD

**Issue by maspotts** [ropensci/rnoaa#182]
Although the NOAA website doesn't mention this, since noon today I've been getting 301 errors from all NOAA API V2 services reporting a move from HTTP to HTTPS.  I've asked the NOAA technical support folks if this is a permanent change, but as long as it's in place I can't get the rnoaa api functions to work.  Example:

```
curl -H token:${MYTOKEN} http://www.ncdc.noaa.gov/cdo-web/api/v2/datasets
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.ncdc.noaa.gov/cdo-web/api/v2/datasets">here</a>.</p>
</body></html>
```

As a quick workaround, is there any way to force an HTTPS connection to any of the ncdc*() family of functions?

**Comment by sckott** [comment]
fixing right now

**Comment by sckott** [comment]
oh, and thanks for the report!

**Comment by sckott** [comment]
@maspotts reinstall from github for now, will send to CRAN today hopefully 

`devtools::install_github("ropensci/rnoaa")`

**Comment by maspotts** [comment]
thanks: works for me.  that was amazingly fast!! :)
