### ISSUE TITLE
coops_search() time_zone weirdness?

### ISSUE THREAD

**Issue by drf5n** [ropensci/rnoaa#184]
```
> ss= coops_search(begin_date=20161210, end_date=20161210,station_name=8638610,product='water_level',datum='NAVD',time_zone='lst')
> ss$data$t[2]
[1] "2016-12-10 00:06:00 EST"
> ss$data$v[2]
[1] -0.453
> ss= coops_search(begin_date=20161210, end_date=20161210,station_name=8638610,product='water_level',datum='NAVD',time_zone='gmt')
> ss$data$t[2]
[1] "2016-12-10 00:06:00 EST"
> ss$data$v[2]
[1] 0.019
> 
```
These are consistent with what you see at https://tidesandcurrents.noaa.gov/waterlevels.html?id=8638610&units=metric&bdate=20161210&edate=20161210&timezone=GMT&datum=NAVD&interval=6&action=data 

I would expect the resultant values to be the same if the times are the same, but the vaues differ while the time remains the same.

If I unclass the resultant time, I see that the timezone attribute exists but is not set:
```
> unclass(ss$data$t[2])
[1] 1481346360
attr(,"tzone")
[1] ""
```
Here, I'd expect the attribute to be set appropriately, as GMT, and EST or EST/EDT for the  Sewells Point Virginia station.  

How should one use the resultant data to get consistent times?

**Comment by sckott** [comment]
thanks for the issue @drf5n 

I'll have a look

**Comment by drf5n** [comment]
My workaround right now is to set the timezone to GMT, do the request, then assign GMT to the returned data:

    Sys.setenv('TZ'='GMT')  # make sure the system time attribute is set.
    Sys.timezone()
    ss= coops_search(begin_date=20161210, end_date=20161210,station_name=8638610,product='water_level',datum='NAVD',time_zone='gmt')
    attr(ss$data$t,'tzone')<-'GMT'  # fix up the time attribute

    ss$data$t[2]
    # [1] "2016-12-10 00:06:00 GMT"
    Sys.setenv('TZ'='EST')  # change TZ to see if it affects the data... nope:
    ss$data$t[2]
    # [1] "2016-12-10 00:06:00 GMT"

**Comment by sckott** [comment]
one problem is that if we need to use LST, that's the local time zone of the station, but they don't give us the time zone of the station in the response. so we have to get it somehow, 

then i can correct the date values given back

**Comment by sckott** [comment]
@drf5n  do you ever use `lst_ldt`?

**Comment by sckott** [comment]
try again after reinstalling

```r
devtools::install_github("ropensci/rnoaa")
library(rnoaa)
ss <- coops_search(begin_date=20161210, end_date=20161210,station_name=8638610,product='water_level',datum='NAVD',time_zone='lst')
ss$data$t[2]
#> [1] "2016-12-10 00:06:00 EST"
rr <- coops_search(begin_date=20161210, end_date=20161210,station_name=8638610,product='water_level',datum='NAVD',time_zone='gmt')
rr$data$t[2]
#> [1] "2016-12-10 00:06:00 GMT"
```

```r
head(ss$data, n = 3)
#>                     t      v     s       f q
#> 1 2016-12-10 00:00:00 -0.458 0.005 0,0,0,0 v
#> 2 2016-12-10 00:06:00 -0.453 0.005 0,0,0,0 v
#> 3 2016-12-10 00:12:00 -0.444 0.004 0,0,0,0 v
rr$data[51:53,]
#>                      t      v     s       f q
#> 51 2016-12-10 05:00:00 -0.458 0.005 0,0,0,0 v
#> 52 2016-12-10 05:06:00 -0.453 0.005 0,0,0,0 v
#> 53 2016-12-10 05:12:00 -0.444 0.004 0,0,0,0 v
```

```r
# convert
ss$data$t <- as.POSIXlt(ss$data$t, tz = "GMT")
```

```r
head(ss$data, n = 3)
#>                     t      v     s       f q
#> 1 2016-12-10 05:00:00 -0.458 0.005 0,0,0,0 v
#> 2 2016-12-10 05:06:00 -0.453 0.005 0,0,0,0 v
#> 3 2016-12-10 05:12:00 -0.444 0.004 0,0,0,0 v
rr$data[51:53,]
#>                      t      v     s       f q
#> 51 2016-12-10 05:00:00 -0.458 0.005 0,0,0,0 v
#> 52 2016-12-10 05:06:00 -0.453 0.005 0,0,0,0 v
#> 53 2016-12-10 05:12:00 -0.444 0.004 0,0,0,0 v
```

**Comment by sckott** [comment]
changes in ddad05b6bf0173ae2ead27de5bac796b6f8b2eb7

**Comment by drf5n** [comment]
Re. LST_LDT, no, I try to always use UTC.

This fix works for me.  Thanks.

**Comment by sckott** [comment]
Glad it works

**Comment by sckott** [comment]
done
