### ISSUE TITLE
Access sea ice CSV data?

### ISSUE THREAD

**Issue by cboettig** [ropensci/rnoaa#194]
Looks like we can access the shapefiles, but it would be nice to just get the sea ice time-series data as well, e.g. ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/north/monthly/data/

Ideally the function would aggregate the separate monthly (or daily) files into single timeseries dataframe.

**Comment by sckott** [comment]
thanks @cboettig will have a look

for timeseries, you mean like with `zoo` package?

**Comment by cboettig** [comment]
No, just reading the CSV into a data.frame is probably best. I just meant the data is just over time and not space in the .CSV files

**Comment by sckott** [comment]
Okay, thanks

**Comment by sckott** [comment]
cc @cboettig fxn `seaice_tabular()` added
