### ISSUE TITLE
Temperature and Dew Point

### ISSUE THREAD

**Issue by zxy1219** [ropensci/rnoaa#204]
`Hi, I have download ISD data for about 100 sites using the rnoaa package. The format of temperature (including dew point) seems in two different formats: one is same to the ReadMe file provided by NOAA, which has been scaled by 10; another one looks like in the Celsius degree formation, no scale.

This issue also happens to the "date" attribute. Anyone experienced the same issue with me? 

```

**Comment by sckott** [comment]
thanks for the issue @zxy1219 

Can you please share your session info and an example of each of the two forms you see

**Comment by zxy1219** [comment]
I have uploaded them here:
https://github.com/zxy1219/Working-Log

**Comment by sckott** [comment]
thanks, will have a look 

can  you share your session info too pleasea

**Comment by sckott** [comment]
@zxy1219 sorry it's been so long. 

so things have changed lots. we now don't do any transformations by default on the output data, and we by default include a lot more columns of data. 

Given those changes it's now hard to compare to those csv files you shared in that repo. 

Given that we don't do any transformations on the data, but simply get the data for the user, i'll close this for now - we can reopen if we're making a mistake somewhere. Do make sure you have the newest version from github. we're sending a new version to cran soon
