### ISSUE TITLE
rnoaa does not include updates provided by NOAA. 

### ISSUE THREAD

**Issue by RafaRafa** [ropensci/rnoaa#210]
Why doesn't the `ncdc()` return include the updated data provided by NOAA? These updated files can be found here: ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/superghcnd/

For example: 

The call:
    `oout <- ncdc(datasetid='GHCND', stationid='GHCND:USC00137859', startdate = '2017-03-27', enddate = '2017-03-29', datatypeid = 'TMAX')`

Returns:

```                     date datatype           station value fl_m fl_q fl_so fl_t
1 2017-03-27T00:00:00     TMAX GHCND:USC00137859   117              H 0700
2 2017-03-29T00:00:00     TMAX GHCND:USC00137859    72               H 0700
```

Note that there is no value for 2017-03-28. However if you go to the corrections (this one is in superghcnd_diff_20170328_to_20170329) provided by NOAA, there is a value for that station for the 28th:
    
    USC00137859 20170328 TMAX 117 H 700

**Comment by sckott** [comment]
thanks for opening the issue @RafaRafa 

I don't know the answer to your question. I can ask my NOAA contacts though and get back to you here

**Comment by sckott** [comment]
@RafaRafa  Didn't get a response yet, will email again some more folks

**Comment by sckott** [comment]
@RafaRafa Sounds like it's updated or will be soon

**Comment by sckott** [comment]
it's fixed now, closing
