### ISSUE TITLE
Local Climatological Data

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#212]
QCLD  
https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/quality-controlled-local-climatological-data-qclcd
 
LCD https://www.ncdc.noaa.gov/cdo-web/datatools/lcd

emailed rich baldwin

so far as I can tell only interface to LCD is a GUI web portal

**Comment by sckott** [comment]
bulk access avail. at https://www.ncei.noaa.gov/data/global-hourly/access/ 

> won't have a public API until 6/30 Q3 release

**Comment by raboinab** [comment]
Any update to this?

**Comment by sckott** [comment]
looks like we can move ahead with this now. will report back when we have a function to try out

**Comment by sckott** [comment]
@raboinab @matttyride @ethankale can you reinstall `devtools::install_github("ropensci/rnoaa")` and try `lcd` function, let me know if we should change anything

**Comment by ethankale** [comment]
Tried out the `lcd` function, worked great.  Interesting note, though - a lot of the columns are actually multiple comma-delimited columns pasted together, and need to be parsed further to separate the QA from the data.  For example:

    d <- lcd(station = "72792024227", year = "2017") %>%
      filter(report_type == "FM-15") %>%
      separate(wnd, c("w.angle", "w.a.qa", "w.type", "w.speed.mps", "w.s.qa"),
               sep = ",", convert=TRUE, remove=TRUE) %>%
      separate(tmp, c("t.degree.c", "t.qa"), 
               sep=",", remove=TRUE) %>%
      separate(aa1, c("p.hours", "p.mm", "p.code", "p.qa"), 
               sep=",", remove=TRUE, convert=TRUE) %>%
      separate(oc1, c("wg.speed.mps", "wg.qa"),
               sep=",", remove=TRUE, convert=TRUE) %>%
      filter(p.hours == 1) %>%
      mutate(dt = as.POSIXct(date, format="%Y-%m-%dT%H:%M:%S", tz="Etc/GMT+8"),
             t.degree.c = as.numeric(t.degree.c)*0.1,
             w.speed.mph = w.speed.mps*0.1*2.23694,
             wg.speed.mps = wg.speed.mps*0.1*2.23694,
             p.in = p.mm*0.1*0.0393701)

**Comment by sckott** [comment]
thanks @ethankale 

right, there is some data to still be cleaned up there. Will have a look into it

**Comment by raboinab** [comment]
This is the ISD data. It is not the LCD data so its a bit misleading. the observations from the ISD to the LCD they don't match. True the LCD originates from ISD but also includes wet bulb temp, hourly visibility, hourly dew point etc...the true label for this argument label is ISD not LCD. FYI

**Comment by sckott** [comment]
@ethankale sorry about long delay on this. trying to get this dialed in. Where did you figure out the parsing for this? Are there docs somewhere i'm not seeing?

**Comment by sckott** [comment]
I think for now I'll just return the data as is and warn uses they have to parse it, but then next version to CRAN will get the parsing worked out
