### ISSUE TITLE
seaice date bug

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#217]
at least locally on my machine the seaice test fails due to this `months()` call https://github.com/ropensci/rnoaa/blob/master/R/seaice.r#L68 

played around a bit but no fix yet. seems like it creates an S4 object unfortunately and thus maybe is related to some problem with `methods`

anyone have a solution

```r
library(lubridate)
pryr::otype(months(1))
#> [1] "S4"
```

**Comment by tphilippi** [comment]
I assume you're trying to get the month.abb for all completed months so far in the current year?  If so,
```
 eachmonth_thiyr <- month.abb[1:(lubridate::month(Sys.Date()))-1]
 eachmonth_thiyr <- month.abb[1:(grep(format(Sys.Date(), "%b"), month.abb) -1 )]
  ```
appear to work.  I'm not sure why you try to shift the date first then extract the 3 letter month.  Is there some irregularity between format(..., "%b") and month.abb in different locales or languages?

**Comment by sckott** [comment]
> I assume you're trying to get the month.abb for all completed months so far in the current year?

yes

if something else works better without the error happy to go with that 

this is the error message 

`trying to get slot "group" from an object of a basic class NULL with no slots`

doesn't happen on travis as that test is skipped on travis

**Comment by tphilippi** [comment]
While my 2 suggestions above work on my computer, I think the cleanest code using only base is:
```
> month.abb[1:(as.numeric(format(Sys.Date(), "%m")) - 1)]
[1] "Jan" "Feb" "Mar"
> Sys.Date()     # to show current month is 4
[1] "2017-04-28"
```

**Comment by sckott** [comment]
thanks @tphilippi

**Comment by sckott** [comment]
this seems sorted now
