### ISSUE TITLE
NOAA ACIS new datasource

### ISSUE THREAD

**Issue by tphilippi** [ropensci/rnoaa#218]
Potential new data source.
Applied Climate Information System
http://www.rcc-acis.org/
API documented at
http://www.rcc-acis.org/docs_webservices.html

This may be the future unified API for NOAA climate data from their Regional Climate Centers.  While some data (e.g., ghcn) are available from other APIs via rnoaa, ACIS appears to have several potential advantages:
* Data from FAA, COOPS, and other stations as well as those in GHCN
* More powerful & flexible tools for discovering stations that meet search criteria
* RCC-specific filters & flags more appropriate for  regional conditions (e.g., locally-appropriate cutoffs for extreme events vs flagging as instrumentation error)
* This API may persist for multiple years into the future.

NPS IMD is working with this API.  I may take a stab at a pair of functions for rnoaa (ACIS_search and ACIS_get ?) later this year.  This is just notification to all about the potential data source.

**Comment by sckott** [comment]
sounds great @tphilippi 

i only ask that fxns stay lowercase `acis_get`, `acis_search`

**Comment by sckott** [comment]
any thoughts on this @tphilippi ?

**Comment by tphilippi** [comment]
I've been working more on species observations the past few months.  I have on my to-do list either helping my colleague who wrote the NPS ACIS R functions wrap them into a stand-alone package, or change the function names, tweak the code style (mostly global replacements for variable names) and submitting to rnoaa.  _Maybe_ I'll take a day or 2 to do this over the holidays, as I have a few weeks of use-or-lose leave, but I'm trying to reserve that time for actually writing a paper, and my alternative (initial) contribution to rOpenSci would be to try to add authentication to rinat akin to that in rgbif, to get rid of my code that has to recursively split spatial queries to get small enough chunks of observations.  Right now authentication for rinat and spinning up downloads in ridigbio akin to occ_download() occ_download_get() in rgbif are higher priorities for my work.  But, dealing with authentication may be beyond my skillset, while I know I can write acis_get functions.
Ping me in January if I haven't done anything by then.

**Comment by sckott** [comment]
Thx for the update and explanation @tphilippi

**Comment by sckott** [comment]
ping @tphilippi

**Comment by sckott** [comment]
ping @tphilippi any thoughts? Is this still going to happen?
