### ISSUE TITLE
Feature request: request data by coordinates (lat/long)

### ISSUE THREAD

**Issue by michaeljakob** [ropensci/rnoaa#226]
Many of my fellow researchers and me extensively use RNOAA and really enjoy it.
However, there is one use case that we all share, but it unfortunately is not natively supported.

Usually I have the `latitude`, `longitude` and a `date`. Now I would love to know one of the variables (e.g. `air_temperature` or `wind_speed`) at that exact location and exact date.
Is there an easy way to get e.g. the `air_temperature` given an exact date and then just select the *nearest station* that measures `air_temperature`. 

I spent the entire day trying to solve this issue and talked to many partners, but none could find a good solution.
Of course, I can query stations by location. Yet, then I typically also select locations that don't have the parameter I need. Or don't have it at the time I need it.
This is the goal function I am looking for (that I was unable after 12 hours to create myself :()

`data$air_temperature = fetch_nearest_parameter(latitude = lat, longitude = lon, date = mydate, parameter = "air_temperature")`

A great helper function to solve that task would be: select the nearest station at lat/long that offers `air_temperature` at my given date. 

This is my latest attempt (not *really* working) is the following.
Step 1: select the 50 nearest stations
Step 2: for all of them, try to grab the air_temperature at my given date. 
Step 3: hope that there is at least 1 match and then use this one. 
Issue with this approach: there never is a single match in Step 3.

```
lat_lon_df <- data.frame(id = c("1"),
                         latitude = c(-33.8675),
                         longitude = c(151.2070))


# fetch 50 nearest stations
nearby_stations <- meteo_nearby_stations(lat_lon_df = lat_lon_df, limit=50,  var = c("TMAX"), 
                                          station_data = station_data, year_min=2000, year_max=2017)
ns <- do.call(rbind, lapply(nearby_stations, data.frame, stringsAsFactors=FALSE))

mydate = 20160503
# check all 50 stations for air_temperature at my given date
# the column 'xxx' always ends up being filled 100 % with NAs
ns$xxx = lapply(ns$id, function(x) { return(tryCatch(coops_search(station_name = x, begin_date=mydate, end_date=mydate, product="air_temperature"), error=function(e) NA)) })

```

**Comment by sckott** [comment]
I'm glad you and others find it useful! 

Are you looking for data specifically from COOPS? With `ncdc_*()` functions you can at least saerch for stations that within a bounding box for given dates and data types - but then a separate search for the actual data.

**Comment by michaeljakob** [comment]
Dear @sckott , can you please give an example of such code that, given `latitude`,`longitude`,`specific_date` would select the nearest possible station with `air_temperature` and return it?
I seem not to find a way to do exactly this, which seems like the most obvious request for this package.

**Comment by michaeljakob** [comment]
Another solution might be to download *all* stations that provide air quality.
Step 2: select all stations that provide air quality on the specific date needed.
Step 3: calculate the distance from my lat/long to the station's location
Step 4: pick the station with the lowest distance

**Comment by sckott** [comment]
@michaeljakob Note that we are constrained by the interfaces to data that NOAA provides. So on the one hand there is the ideal way to do something (but that ideal way may vary among people) - and on the other hand, there is what we can do within the constraints of what's possible to do with what NOAA provides. 

e.g., here:

```r
library(rnoaa)
res <- ncdc_stations(datasetid = "GHCND", datatypeid = "TMAX", 
                     startdate = "20000101", enddate = "20171231",
                     extent = c(-38.3627, 145.7963, -29.3723, 156.6177))
ncdc(datasetid = "GHCND", stationid = res$data$id[1], 
     startdate = '2010-01-01', enddate = '2010-12-31', datatypeid = "TMAX", 
     limit = 500)
```

you can take a point location you're interested in and make a bounding box (numerous ways to do that) - to feed into `ncdc_stations`

-----

> Another solution might be to download all stations that provide air quality.
Step 2: select all stations that provide air quality on the specific date needed.
Step 3: calculate the distance from my lat/long to the station's location
Step 4: pick the station with the lowest distance

I assume the "download all stations" relates to #227 ?

That does seem like a good solution assuming there's a good way to get that list of stations with lat/long

`ghcnd_stations()` and `isd_stations()` might help - those functions do a bulk download of all GHCND and ISD stations - which may overlap with what you need

**Comment by sckott** [comment]
What about 


```r

library(rnoaa)
statenv <- new.env()
fetch_nearest_parameter <- function(latitude, longitude, date, element, radius = NULL, ...) {
  if (is.null(statenv$station_data)) {
    statenv$station_data <- ghcnd_stations()
  }
  lldf <- data.frame(id = 1, latitude = latitude, longitude = longitude)
  yr <- as.numeric(format(as.Date(date), "%Y"))
  xx <- meteo_nearby_stations(lat_lon_df = lldf, var = element, 
                              station_data = statenv$station_data, 
                              year_min = yr, year_max = yr + 1, radius = radius, ...)
  ns <- dplyr::bind_rows(xx)
  dat <- meteo_pull_monitors(ns$id, var = "TMAX", 
                             date_min = date, date_max = date)
  dplyr::left_join(dat, ns, by = "id")
}
```

```r
fetch_nearest_parameter(latitude = -33.8675, longitude = 151.2070,
                        date = "2016-05-03", element = "TMAX", radius = 10)
```

```r
# A tibble: 4 x 7
           id       date  tmax                           name latitude longitude  distance
        <chr>     <date> <dbl>                          <chr>    <dbl>     <dbl>     <dbl>
1 ASN00066062 2016-05-03   264      SYDNEY (OBSERVATORY HILL) -33.8607  151.2050 0.7783486
2 ASN00066196 2016-05-03   252 SYDNEY HARBOUR (WEDDING CAKE W -33.8414  151.2633 5.9540769
3 ASN00066037 2016-05-03   269             SYDNEY AIRPORT AMO -33.9465  151.1731 9.3248624
4 ASN00066194 2016-05-03   256      CANTERBURY RACECOURSE AWS -33.9057  151.1134 9.6276700
```

**Comment by michaeljakob** [comment]
@sckott Thank you so much, I really love this solution.
In your first snippet you can also replace the `var="TMAX"` in the function call of `metea_pull_monitors` to make the entire function truly generic (otherwise, even if you supply "TMIN" as `element` it would still return "TMAX".

**Comment by sckott** [comment]
great, glad you like it, the var=tmax was an oversight, meant to have `element` param pass on to that `var` param
