### ISSUE TITLE
Is there a way to search for US airport weather stations?

### ISSUE THREAD

**Issue by andypicke** [ropensci/rnoaa#234]
I'm interested in getting historical daily weather data from US airport stations.

**Comment by sckott** [comment]
hi @andypicke so sorry about such a long delay in answering 

i believe there is, i'll get an answer to you in the morning ...

**Comment by sckott** [comment]
does this help https://discuss.ropensci.org/t/search-for-us-airport-weather-stations-w-rnoaa/1034

**Comment by jsta** [comment]
Works great! After that you can pull the data with `meteo_pull_monitors`. Its too bad that the minimum available date on most of these is fairly recent.

**Comment by sckott** [comment]
@jsta thx for the tip about pulling the dat. bummer, didn't look at the dates :(
