### ISSUE TITLE
blended sea winds

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#246]
https://www.ncdc.noaa.gov/data-access/marineocean-data/blended-global/blended-sea-winds

FTP ftp://eclipse.ncdc.noaa.gov/pub/seawinds/

on google scholar https://scholar.google.com/scholar?q=%22blended+Sea+Winds%22&hl=en&as_sdt=1%2C38&as_vis=1&as_ylo=&as_yhi=

OPeNDAP/THREDDS server https://www.ncei.noaa.gov/thredds/blended-global/oceanWinds.html

**Comment by sckott** [comment]
just handling netcdf files for now, not dealing with http://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/ieee.html files

**Comment by sckott** [comment]
done in 00b9690c78ff2527be69c6e682f0292f89be9c19

**Comment by ksaha79** [comment]
The Blended wind data is developed into a newer (Version 2) and better product available through:
https://coastwatch.noaa.gov/cwn/products/noaa-ncei-blended-seawinds-nbs-v2.html

**Comment by djhocking** [comment]
Thanks. NOAA remade their entire suite of APIs related to weather. I am going to have to build a new package ASAP. I'll add this to the list of APIs. At least it's all much more centralized and unified. Thanks.
