### ISSUE TITLE
rnoaa installation

### ISSUE THREAD

**Issue by jfpeters** [ropensci/rnoaa#271]
I am having difficulty installing rnoaa package.  I'm getting the following response (truncated):

<ERROR: dependencies 'crul', 'lubridate', 'XML' are not available for package 'rnoaa'>

I've tried installing the dependency packages above individually, but that doesn't work either,  Any assistance would be appreciated.

Thanks! - James

```r

```
</details>

**Comment by jsta** [comment]
Can you post the output of `sessionInfo()`? It would help to know your R version and OS.

**Comment by jfpeters** [comment]
R version 3.2.0 (2015-04-16)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arcgisbinding_1.0.0.128

loaded via a namespace (and not attached):
[1] tools_3.2.0

**Comment by jfpeters** [comment]
Updating the version of R to 3.5.1. and then reinstalling the 'rnoaa' API did the trick.  Thank you!

Now just have to update my R-ArcGIS bridge installation...

**Comment by sckott** [comment]
thanks for your question @jfpeters and thanks for the problem solving @jsta !
