### ISSUE TITLE
ncdc_stations requires charset=UTF-8 ERROR

### ISSUE THREAD

**Issue by mattplulu** [ropensci/rnoaa#297]
When I use the 'ncdc_stations()' function it returns the error:
Error in check_response(temp) : 
  x$headers$`content-type` == "application/json;charset=UTF-8" is not TRUE

This happens no matter what parameters are used in the function. Even the example use of the function in the RNOAA package discription PDF returns this error:  
ncdc_stations(stationid='COOP:010008')
This was not the case when I ran the exact code in early Dec 2018 and it worked great. I have also tried updating my r version (to: 3.5.2) and the package and it produces the same issue. Perhaps the last package update bug? or perhaps Government Shutdown? Thanks

**Comment by sckott** [comment]
hi @mattplulu - thanks for opening an issue. 

This is because of the government shutdown. 

reinstall from github `remotes::install_github("ropensci/rnoaa")`, restart R, then try again, and you should get a nicer error message, let me know if it works.

**Comment by sckott** [comment]
as for the data you want, most NOAA data thats served via FTP is still available. i should make a table of NOAA data sources in his pkg and where data comes from for each of them
