### ISSUE TITLE
Along-track significant wave height, wind speed and sea level anomaly from multiple altimeters

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/rnoaa#308]
Cool newer (from 2017) dataset combining interpolated data from multiple sensors for sea surface height and sea surface height anomaly. Datasets look easily accessible.

https://coastwatch.noaa.gov/cw/satellite-data-products/sea-surface-height.html

**Comment by sckott** [comment]
thanks @jebyrnes !

you're interested in both https://coastwatch.noaa.gov/cw/satellite-data-products/sea-surface-height/along-track.html and https://coastwatch.noaa.gov/cw/satellite-data-products/sea-surface-height/optimal-interpolation-level-3-sea-level-anomalies-from-multiple-altimeter-missions.html or just one of those?

**Comment by sckott** [comment]
started working on this on a branch, the file names are a mystery though as per usual

if anyone wants to chime in with how to interpret the file names, wrt translating into a user interface in an R function, that'd be great

**Comment by sckott** [comment]
closing unless someone wants to try doing this,
