### ISSUE TITLE
Error: package or namespace load failed for ‘rnoaa’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  namespace ‘curl’ 3.2 is already loaded, but >= 3.3 is required

### ISSUE THREAD

**Issue by zxy1219** [ropensci/rnoaa#310]
I installed the rnoaa using code:
`devtools::install_github("ropensci/rnoaa")
`
Then I run the library, an error reminder come out:
 `library('rnoaa')`
Error: package or namespace load failed for ‘rnoaa’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘curl’ 3.2 is already loaded, but >= 3.3 is required
In addition: Warning message:
package ‘rnoaa’ was built under R version 3.5.3

**Comment by sckott** [comment]
you just need to install a more recent version of curl `install.packages("curl")`
