### ISSUE TITLE
Include gaps in coverage plots

### ISSUE THREAD

**Issue by philipshirk** [ropensci/rnoaa#314]
I'm not sure if this really belongs in the issues or the forum, since it's more a feature request than a bug, but here it goes. In some cases stations are missing a lot of data, making the `autoplot()` of a `meteo_coverage` object very misleading. For example: 

```{r}
library(rnoaa)
library(ggplot2)

# Site
Safe_Harbor <-  'USC00367732'

# get data
dat <- meteo_pull_monitors(monitors =  Safe_Harbor, 
                            keep_flags = T, 
                            var = c("PRCP", "TAVG", "TMAX", "TMIN"))

# autoplot plots from first to last date, ignoring gaps
obs_covr <- meteo_coverage(meteo_df = dat)
autoplot(obs_covr)

# Alternative plot, showing gaps
# unique dates
min_date <- min(dat$date)
max_date <- max(dat$date)
dates <- data.frame(date = as.Date(x = seq.Date(from = min_date,
to = max_date, 
by = 'day')))
# join the original data to all the unique dates
temp <- dplyr::full_join(x = dates,
y = dat,
by='date')
temp$location <- Safe_Harbor

# dummy column for plotting
temp$size <- NA
temp$size[which(!is.na(temp$prcp))] <- 1

# plot with gaps in coverage
ggplot(temp, aes(x = date, y = location, size = size))+
   theme_bw()+
   geom_line(show.legend = F)
```

**Comment by sckott** [comment]
Thanks for the issue @filups - Sorry for any confusion: this is a great place to open issues regarding bugs, features, use cases, etc. Not just bug reports. 

@geanders do you have any thoughts on this?  plotting stuff is not one of my skills, and you were the original author of this i think

it makes sense to me to make this change to account for gaps

**Comment by sckott** [comment]
@filups if you have time, could you send a pull request with your proposed changes?

**Comment by filups** [comment]
I'll see what I can do. Could you save me a bit of time by pointing me towards where I can find the code for the `autoplot` function and some info on the `meteo_coverage` output structure?

**Comment by sckott** [comment]
great, thanks.

`autoplot.meteo_coverage` is in https://github.com/ropensci/rnoaa/blob/master/R/meteo-autoplot.R

`meteo_coverage` is in https://github.com/ropensci/rnoaa/blob/master/R/meteo_utils.r

**Comment by philipshirk** [comment]
I (finally) started working on this. The easiest and most efficient thing to do will be to change the output from `meteo_coverage` from a data.frame to a list (or at least a different data.frame). Are there any other functions (other than `autoplot.meteo_coverage`) that use the output from meteo_coverage that might have a problem with that?

**Comment by sckott** [comment]
@philipshirk  Great, glad to hear it. Looks like `meteo_coverage` is only used for autoplot - so we are free to change it outputs
