### ISSUE TITLE
gefs example failing

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#320]
@potterzot this example in the gefs docs is failing now, does it do the same for you?

```r
#Fetch a different date (available up to 10 days prior to today)
forecast_yesterday_prec <- gefs(
   "Total_precipitation_surface_6_Hour_Accumulation_ens",
   lat, lon, date=format(as.Date(Sys.time()) - 1, "%Y%m%d"))

#> Error in Rsx_nc4_get_vara_double: NetCDF: Index exceeds dimension bound
#> Var: Total_precipitation_surface_6_Hour_Accumulation_ens  Ndims: 4   Start: 0,0,44,242 Count: 65,21,1,1
#> Error in ncvar_get_inner(ncid2use, varid2use, nc$var[[li]]$missval, addOffset,  :
#>   C function R_nc4_get_vara_double returned error
```

**Comment by potterzot** [comment]
Thanks @sckott. That specific variable has a different time dimension variable name with different values, which the default set of values for time_idx was exceeding. Have made some changes to set the default dynamically depending on the size of the dimensions associated with each variable.

**Comment by sckott** [comment]
ok, thanjs
