### ISSUE TITLE
worldwide altitude/hypsography data

### ISSUE THREAD

**Issue by hsiehph** [ropensci/rnoaa#325]
Hello,

I apologize if I am not at the right place to ask the following question.
I am interested in gathering altitude/ hypsography data for a set of geographic locations across the world. I found that the following project seems to have the data I look for, but neither am I sure how to use it nor I know how to apply rnoaa to it. I would be grateful if you can point me to the right tool/resource for me.

https://www.ngdc.noaa.gov/mgg/topo/globe.html

Thanks,
PingHsun

**Comment by sckott** [comment]
thanks for the issue @hsiehph  - this probably isn't something we would include in rnoaa since it's not climate data, but we can see if anyone knows if it's already avail. in another R pkg. 

@amoeba @mbjoseph @jsta @tphilippi anyone know if this NOAA Global Land One-km Base Elevation Project data is avail in any R pkgs already?

**Comment by sckott** [comment]
skin temperature? can you explain what that means

**Comment by hsiehph** [comment]
oops.... I meant to say temperature. Autocompletion sneakily added skin
into the sentence. sorry

**Comment by sckott** [comment]
> one-km base or similar resolution across the world

I'm not familiar with the resolutions of the datasets available here, you could look at the different data sources avail. https://github.com/ropensci/rnoaa#data-sources-in-rnoaa and see what their resolutions are

**Comment by mbjoseph** [comment]
@hsiehph for acquiring altitude data in R I would recommend the elevatr package: https://github.com/jhollist/elevatr

The elevatr package will pull data from a different source (either USGS or AWS terrain tiles depending on location), but it might solve your issue.

**Comment by sckott** [comment]
thanks @mbjoseph

**Comment by hsiehph** [comment]
Thanks, everyone for the suggestions. Sorry I was away for conferences in
the past several days. I will try some of the packages mentioned and see
how it goes.

Thanks!
