### ISSUE TITLE
Unit of temperature/dew downloaded using isd()

### ISSUE THREAD

**Issue by zxy1219** [ropensci/rnoaa#329]
I use the isd() function to download the hourly ISD data. In the downloaded dataset, the temperature and dew point ranged from -250 to 350. It seems not in any of the units of temperature (fahrenheit, celsius or Kelvin). I'm wondering what would be the unit of the temperature in the downloaded data?

**Comment by sckott** [comment]
thanks, but session info please [as requested](https://github.com/ropensci/rnoaa/issues/new)

**Comment by sckott** [comment]
@zxy1219 session info?
