### ISSUE TITLE
Can't obtain API key

### ISSUE THREAD

**Issue by drwawa** [ropensci/rnoaa#337]
Hi all,

Going to https://www.ncdc.noaa.gov/cdo-web/token brings up a proxy error listed below:

### START message
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /cdo-web/token.

Reason: Error reading from remote server

Additionally, a 502 Bad Gateway error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by sckott** [comment]
it looks like they are doing maintainence for this week- See the banner at the top of https://www.ncdc.noaa.gov/

![Screen Shot 2019-11-26 at 2 27 28 PM](https://user-images.githubusercontent.com/577668/69677937-0168ca80-1059-11ea-8d92-5442fcae25f3.png)


You probably need to wait until the site is working again

**Comment by sckott** [comment]
Some, possibly all, of the data behind the `ncdc` functions are available via some of the other fxns in rnoaa, just through a different source, the interfaces are different though

**Comment by sckott** [comment]
looks like https://www.ncdc.noaa.gov/cdo-web/token is working again
