### ISSUE TITLE
API key 

### ISSUE THREAD

**Issue by jdpeiffer6** [ropensci/rnoaa#339]
Hi there,

The link found on most pages to request an API key does not appear to work: https://www.ncdc.noaa.gov/cdo-web/token.

Is there another way to get an API key?

Thanks,

JD

**Comment by sckott** [comment]
NOAA is doing some maintanence, so that site is down right now - dont know of any other way to get a token

**Comment by jdpeiffer6** [comment]
Sounds good,

Sorry, should have read the other forums first!

Thanks,

JD

**Comment by sckott** [comment]
looks like https://www.ncdc.noaa.gov/cdo-web/token is working again

**Comment by jdpeiffer6** [comment]
Great thanks!

JD
