### ISSUE TITLE
Error from coops_search(product = "predictions") for any time zone argument other than "gmt"

### ISSUE THREAD

**Issue by Maggie-Mason** [ropensci/rnoaa#342]
I have a nearly identical script using product = "water_level", time_zone = "lst_ldt" with no issue. Trying to request tide predictions with any time zone argument other than "gmt" produces the error at the bottom. Currently I can request it as GMT then convert the datetime to EST, but that means my data call is starting and ending a quarter day off from what I want for my EST station.  

```
> may.tides <- (coops_search(station_name = 8551762, 
+                                           begin_date = 20200501, end_date = 20200531, 
+                                           datum = "mtl", product = "predictions", units = "metric", time_zone = "lst_ldt"))

Error in if (!repeated && grepl("%[[:xdigit:]]{2}", URL, useBytes = TRUE)) return(URL) : 
  missing value where TRUE/FALSE needed
```

**Comment by sckott** [comment]
Can you please share your `sessionInfo()` (or `devtools::session_info()`) as requested
