### ISSUE TITLE
homr() gives Error: Bad gateway (HTTP 502)

### ISSUE THREAD

**Issue by windnick** [ropensci/rnoaa#384]
Recent changes to NOAA server cause HTTP 502 error. Blog posts suggest this can be avoided by forcing HTTP  version 1.0

<details> <summary><strong>Session Info</strong></summary>

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rnoaa_1.1.0          RevoUtils_11.0.2     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       xml2_1.3.2       magrittr_1.5     rappdirs_0.3.1  
 [5] tidyselect_1.1.0 munsell_0.5.0    colorspace_1.4-1 R6_2.3.0        
 [9] rlang_0.4.6      hoardr_0.5.2     dplyr_1.0.0      grid_4.0.2      
[13] gtable_0.3.0     ellipsis_0.3.1   digest_0.6.25    httpcode_0.3.0  
[17] tibble_3.0.2     lifecycle_0.2.0  crayon_1.3.4     gridExtra_2.3   
[21] tidyr_1.1.0      purrr_0.3.4      ggplot2_3.3.2    vctrs_0.3.1     
[25] triebeard_0.3.0  curl_3.3         crul_0.9.0       glue_1.4.1      
[29] compiler_4.0.2   pillar_1.4.6     urltools_1.7.3   generics_0.0.2  
[33] scales_1.1.1     XML_3.99-0.4     lubridate_1.7.9  jsonlite_1.5    
[37] pkgconfig_2.0.3 </strong></summary>
```

</details>

**Comment by sckott** [comment]
I see you're using an older version of rnoaa, try upating to latest rnoaa on cran and try again - if that still doens't work share a reproducible example - see https://reprex.tidyverse.org/ if you aren't sure how to do it

**Comment by windnick** [comment]
Argh! Default ROpen repos is 7 months out of date!  Installed rnoaa_1.3.0 from GitHub, but same HTTP 502 error. Presume one or more dependencies are also out of date. Which?

> library(rnoaa)
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rnoaa_1.3.0          RevoUtils_11.0.2     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       xml2_1.3.2       magrittr_1.5     rappdirs_0.3.1  
 [5] tidyselect_1.1.0 munsell_0.5.0    colorspace_1.4-1 R6_2.3.0        
 [9] rlang_0.4.6      hoardr_0.5.2     dplyr_1.0.0      tools_4.0.2     
[13] grid_4.0.2       gtable_0.3.0     ellipsis_0.3.1   digest_0.6.25   
[17] httpcode_0.3.0   tibble_3.0.2     lifecycle_0.2.0  crayon_1.3.4    
[21] gridExtra_2.3    tidyr_1.1.0      purrr_0.3.4      ggplot2_3.3.2   
[25] vctrs_0.3.1      curl_3.3         crul_0.9.0       glue_1.4.1      
[29] compiler_4.0.2   pillar_1.4.6     generics_0.0.2   scales_1.1.1    
[33] XML_3.99-0.4     lubridate_1.7.9  jsonlite_1.5     pkgconfig_2.0.3 
> x<-homr(quid="ICAO:KIAD")
Error: Bad Gateway (HTTP 502)
>

**Comment by sckott** [comment]
Lets see if it's a general problem with your setup. do any of these work?

```r
library(rnoaa)
ghcnd(stationid = "AGE00147704")
lcd(station = "01338099999", year = 2015)
bsw(date = "2017-10-01")
```

**Comment by windnick** [comment]
Thanks for your help. Response to your code is:

> library(rnoaa)
> ghcnd(stationid = "AGE00147704")
using cached file: C:\Users\swift\AppData\Local\Cache/R/noaa_ghcnd/AGE00147704.dly
date created (size, mb): 2021-02-05 10:33:37 (0.487)
 A tibble: 963 x 128
   id     year month element VALUE1 MFLAG1 QFLAG1 SFLAG1 VALUE2 MFLAG2 QFLAG2
   <chr> <int> <int> <chr>    <int> <chr>  <chr>  <chr>   <int> <chr>  <chr> 
 1 AGE0~  1909    11 TMAX        NA " "    " "    " "        NA " "    " "   
 2 AGE0~  1909    11 TMIN        NA " "    " "    " "        NA " "    " "   
 3 AGE0~  1909    11 PRCP        NA " "    " "    " "        NA " "    " "   
 4 AGE0~  1909    12 TMAX       170 " "    " "    "E"       160 " "    " "   
 5 AGE0~  1909    12 TMIN        90 " "    " "    "E"       100 " "    " "   
 6 AGE0~  1909    12 PRCP        24 " "    " "    "E"         0 " "    " "   
 7 AGE0~  1910     1 TMAX       140 " "    " "    "E"       120 " "    " "   
 8 AGE0~  1910     1 TMIN       100 " "    " "    "E"        80 " "    " "   
 9 AGE0~  1910     1 PRCP        82 " "    " "    "E"       176 " "    " "   
10 AGE0~  1910     2 TMAX       110 " "    " "    "E"       140 " "    " "   
 ... with 953 more rows, and 117 more variables: SFLAG2 <chr>, VALUE3 <int>,
   MFLAG3 <chr>, QFLAG3 <chr>, SFLAG3 <chr>, VALUE4 <int>, MFLAG4 <chr>,
   QFLAG4 <chr>, SFLAG4 <chr>, VALUE5 <int>, MFLAG5 <chr>, QFLAG5 <chr>,
   SFLAG5 <chr>, VALUE6 <int>, MFLAG6 <chr>, QFLAG6 <chr>, SFLAG6 <chr>,
   VALUE7 <int>, MFLAG7 <chr>, QFLAG7 <chr>, SFLAG7 <chr>, VALUE8 <int>,
   MFLAG8 <chr>, QFLAG8 <chr>, SFLAG8 <chr>, VALUE9 <int>, MFLAG9 <chr>,
   QFLAG9 <chr>, SFLAG9 <chr>, VALUE10 <int>, MFLAG10 <chr>, QFLAG10 <chr>,
   SFLAG10 <chr>, VALUE11 <int>, MFLAG11 <chr>, QFLAG11 <chr>, SFLAG11 <chr>,
   VALUE12 <int>, MFLAG12 <chr>, QFLAG12 <chr>, SFLAG12 <chr>, VALUE13 <int>,
   MFLAG13 <chr>, QFLAG13 <chr>, SFLAG13 <chr>, VALUE14 <int>, MFLAG14 <chr>,
   QFLAG14 <chr>, SFLAG14 <chr>, VALUE15 <int>, MFLAG15 <chr>, QFLAG15 <chr>,
   SFLAG15 <chr>, VALUE16 <int>, MFLAG16 <chr>, QFLAG16 <chr>, SFLAG16 <chr>,
   VALUE17 <int>, MFLAG17 <chr>, QFLAG17 <chr>, SFLAG17 <chr>, VALUE18 <int>,
   MFLAG18 <chr>, QFLAG18 <chr>, SFLAG18 <chr>, VALUE19 <int>, MFLAG19 <chr>,
   QFLAG19 <chr>, SFLAG19 <chr>, VALUE20 <int>, MFLAG20 <chr>, QFLAG20 <chr>,
   SFLAG20 <chr>, VALUE21 <int>, MFLAG21 <chr>, QFLAG21 <chr>, SFLAG21 <chr>,
   VALUE22 <int>, MFLAG22 <chr>, QFLAG22 <chr>, SFLAG22 <chr>, VALUE23 <int>,
   MFLAG23 <chr>, QFLAG23 <chr>, SFLAG23 <chr>, VALUE24 <int>, MFLAG24 <chr>,
   QFLAG24 <chr>, SFLAG24 <chr>, VALUE25 <int>, MFLAG25 <chr>, QFLAG25 <chr>,
   SFLAG25 <chr>, VALUE26 <int>, MFLAG26 <chr>, QFLAG26 <chr>, SFLAG26 <chr>,
   VALUE27 <int>, MFLAG27 <chr>, QFLAG27 <chr>, ...
Warning message:
`...` is not empty.

We detected these problematic arguments:
* `needs_dots`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument? 
> lcd(station = "01338099999", year = 2015)
using cached file: C:\Users\swift\AppData\Local\Cache/R/noaa_lcd/2015_01338099999.csv
date created (size, mb): 2021-02-05 10:34:08 (4.177)
 A tibble: 8,096 x 121
   station date  latitude longitude elevation name  report_type source
     <int> <chr>    <dbl>     <dbl>     <dbl> <chr> <chr>        <int>
 1  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 2  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 3  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 4  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 5  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 6  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 7  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 8  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 9  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
10  1.34e9 2015~     61.2      6.65        51 VANG~ FM-12            4
 ... with 8,086 more rows, and 113 more variables:
   hourlyaltimetersetting <lgl>, hourlydewpointtemperature <int>,
   hourlydrybulbtemperature <int>, hourlyprecipitation <lgl>,
   hourlypresentweathertype <chr>, hourlypressurechange <dbl>,
   hourlypressuretendency <int>, hourlyrelativehumidity <int>,
   hourlyskyconditions <chr>, hourlysealevelpressure <chr>,
   hourlystationpressure <chr>, hourlyvisibility <dbl>,
   hourlywetbulbtemperature <int>, hourlywinddirection <int>,
   hourlywindgustspeed <int>, hourlywindspeed <int>, sunrise <lgl>,
   sunset <lgl>, dailyaveragedewpointtemperature <lgl>,
   dailyaveragedrybulbtemperature <lgl>, dailyaveragerelativehumidity <lgl>,
   dailyaveragesealevelpressure <lgl>, dailyaveragestationpressure <lgl>,
   dailyaveragewetbulbtemperature <lgl>, dailyaveragewindspeed <lgl>,
   dailycoolingdegreedays <lgl>,
   dailydeparturefromnormalaveragetemperature <lgl>,
   dailyheatingdegreedays <lgl>, dailymaximumdrybulbtemperature <lgl>,
   dailyminimumdrybulbtemperature <lgl>, dailypeakwinddirection <lgl>,
   dailypeakwindspeed <lgl>, dailyprecipitation <lgl>, dailysnowdepth <lgl>,
   dailysnowfall <lgl>, dailysustainedwinddirection <lgl>,
   dailysustainedwindspeed <lgl>, dailyweather <lgl>, monthlyaveragerh <lgl>,
   monthlydayswithgt001precip <lgl>, monthlydayswithgt010precip <lgl>,
   monthlydayswithgt32temp <lgl>, monthlydayswithgt90temp <lgl>,
   monthlydayswithlt0temp <lgl>, monthlydayswithlt32temp <lgl>,
   monthlydeparturefromnormalaveragetemperature <lgl>,
   monthlydeparturefromnormalcoolingdegreedays <lgl>,
   monthlydeparturefromnormalminimumtemperature <lgl>,
   monthlydeparturefromnormalprecipitation <lgl>,
   monthlydewpointtemperature <lgl>, monthlygreatestprecip <lgl>,
   monthlygreatestprecipdate <lgl>, monthlygreatestsnowdepth <lgl>,
   monthlygreatestsnowdepthdate <lgl>, monthlygreatestsnowfall <lgl>,
   monthlygreatestsnowfalldate <lgl>, monthlymaxsealevelpressurevalue <lgl>,
   monthlymaxsealevelpressurevaluedate <lgl>,
   monthlymaxsealevelpressurevaluetime <lgl>, monthlymaximumtemperature <lgl>,
   monthlymeantemperature <lgl>, monthlyminsealevelpressurevalue <lgl>,
   monthlyminsealevelpressurevaluedate <lgl>,
   monthlyminsealevelpressurevaluetime <lgl>, monthlyminimumtemperature <lgl>,
   monthlysealevelpressure <lgl>, monthlystationpressure <lgl>,
   monthlytotalliquidprecipitation <lgl>, monthlytotalsnowfall <lgl>,
   monthlywetbulb <lgl>, awnd <lgl>, cdsd <lgl>, cldd <lgl>, dsnw <lgl>,
   hdsd <lgl>, htdd <lgl>, normalscoolingdegreeday <lgl>,
   normalsheatingdegreeday <lgl>, shortdurationenddate005 <lgl>,
   shortdurationenddate010 <lgl>, shortdurationenddate015 <lgl>,
   shortdurationenddate020 <lgl>, shortdurationenddate030 <lgl>,
   shortdurationenddate045 <lgl>, shortdurationenddate060 <lgl>,
   shortdurationenddate080 <lgl>, shortdurationenddate100 <lgl>,
   shortdurationenddate120 <lgl>, shortdurationenddate150 <lgl>,
   shortdurationenddate180 <lgl>, shortdurationprecipitationvalue005 <lgl>,
   shortdurationprecipitationvalue010 <lgl>,
   shortdurationprecipitationvalue015 <lgl>,
   shortdurationprecipitationvalue020 <lgl>,
   shortdurationprecipitationvalue030 <lgl>,
   shortdurationprecipitationvalue045 <lgl>,
   shortdurationprecipitationvalue060 <lgl>,
   shortdurationprecipitationvalue080 <lgl>,
   shortdurationprecipitationvalue100 <lgl>,
   shortdurationprecipitationvalue120 <lgl>, ...
Warning message:
`...` is not empty.

We detected these problematic arguments:
* `needs_dots`

These dots only exist to allow future extensions and should be empty.
Did you misspecify an argument? 
> bsw(date = "2017-10-01")
Error: Could not resolve host: eclipse.ncdc.noaa.gov
> 
> homr(quid="ICAO:KIAD")
Error: Bad Gateway (HTTP 502)
> homr(quid="COOP:448903")
Error: Bad Gateway (HTTP 502)
> homr(quid="WBAN:93738")
Error: Bad Gateway (HTTP 502)
> 
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rnoaa_1.3.0          RevoUtils_11.0.2     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.2    tools_4.0.2      
 [5] digest_0.6.25     jsonlite_1.5      lubridate_1.7.9   lifecycle_0.2.0  
 [9] tibble_3.0.2      gtable_0.3.0      pkgconfig_2.0.3   rlang_0.4.6      
[13] cli_2.0.2         crul_0.9.0        curl_3.3          gridExtra_2.3    
[17] dplyr_1.0.0       xml2_1.3.2        generics_0.0.2    vctrs_0.3.1      
[21] rappdirs_0.3.1    triebeard_0.3.0   grid_4.0.2        tidyselect_1.1.0 
[25] glue_1.4.1        httpcode_0.3.0    data.table_1.12.8 R6_2.3.0         
[29] fansi_0.4.1       XML_3.99-0.4      ggplot2_3.3.2     purrr_0.3.4      
[33] tidyr_1.1.0       hoardr_0.5.2      magrittr_1.5      scales_1.1.1     
[37] urltools_1.7.3    ellipsis_0.3.1    assertthat_0.2.1  colorspace_1.4-1 
[41] utf8_1.1.4        munsell_0.5.0     crayon_1.3.4     
>

**Comment by sckott** [comment]
Okay, i think it's just that some NOAA services are very unreliable; sometimes they work and sometimes they do not work. If `homr` never works for you that suggests a different problem, but if it sometimes works then we can't do much about that since that's a NOAA problem that we can't solve

**Comment by windnick** [comment]
Well, I guess the only solution when it's Someone Else's Problem is the write one's own code.
The following will retrieve most useful ASOS station metadata from NOAA HOMR server.

library(stringr)
library(lubridate)

metaASOS=function(qid)
{#----------------------------------- local functions -------------------------------------
    numextract <- function(string){str_extract(string, "\\-*\\d+\\.*\\d*")} 
	# return n characters after expr from str 
   Seg=function(expr,n,str)  
	{if (length(str)>1) str<-paste(str,collapse="")
	 y<-gregexpr(expr,str)
	 i<-unlist(y)+nchar(expr)
        ni<-length(i)
	 s<-character()
        for (j in c(1:ni)) {s<-append(s,substr(str,i[j],i[j]+n-1))}
	 return(s)
	}
	# return integer within n characters of expr in str
    Id<-function(expr,n,str)  
      {s<-Seg(expr,n,str)[1]
       s<-gsub("[^0-9]", "", s)
	 return(as.numeric(s))
 	}
	# return first character string within n characters of expr in str
    Str<-function(expr,n,str) 
    	{s<-Seg(expr,n,str)[1]
       i<-gregexpr('[A-Z]',s,ignore.case=TRUE)[[1]][1] 
       s<-substr(s,i,n)
       i<-gregexpr('\"',s)[[1]][1]
       return(substr(s,1,i-1))
      }
 #------------------------------------ get homr page for qid ----------------------------------
 url<-paste('http://ncdc.noaa.gov/homr/services/station/search?qid=',qid,'&date=all',sep="")
 options(warn=-1)
 homr<-readLines(url)
 options(warn=0)
 #------------------------------------ get current station name, etc ---------------------------
 expr<-'\",\"names\":\\[\\{\"name\"'
 StnName<-Str(expr,100,homr)
 county<-Str('county',100,homr)
 s<-Seg('stateProvinces',100,homr);  state<-Str('stateProvince',100,s)
 #---------------------------------------- UTC offset --------------------------------------
 s<-Seg('utcOffsets',25,homr); Hoffset<-as.numeric(numextract(s))[1]
 # ------------------------------------ get station Id codes ------------------------------
 NCDC<-Id('ncdcStnId',20,homr)
 COOP<-Id('\"COOP\",\"id\":\"',10,homr)
 WBAN<-Id('\"WBAN\",\"id\":\"',10,homr)
 WMO<-Id('\"WMO\",\"id\":\"',10,homr)
 ICAO<-Seg('\"ICAO\",\"id\":\"',4,homr)[1]
 FAA<-substr(ICAO,2,4)
 #---------------------------------------- get latitudes and longitudes ------------------ 
 expr<-'latitude_dec\":\"'
 s<-Seg(expr,100,homr)
 s<-s[grepl("beginDate",s)]	# latitude strings with begin date
 latitudes<-as.numeric(numextract(substr(s,1,15)))
 dates<-Seg('beginDate\":\"',10,s)
 latDates<-make_datetime(as.numeric(substr(dates,1,4)),
		as.numeric(substr(dates,6,7)),as.numeric(substr(dates,9,10)))
 expr<-'longitude_dec\":\"'
 s<-Seg(expr,100,homr)
 s<-s[grepl("beginDate",s)]	# longitude strings with begin date
 longitudes<-as.numeric(numextract(substr(s,1,15)))
 dates<-Seg('beginDate\":\"',10,s)
 longDates<-make_datetime(as.numeric(substr(dates,1,4)),
		as.numeric(substr(dates,6,7)),as.numeric(substr(dates,9,10)))
 # --------------------------------------- get Sonic install date -----------------------
 expr<-'ANEMSONIC';  s<-Seg(expr,50,homr)
 expr<-'beginDate';  s<-Seg(expr,15,s)
 s<-substr(tail(s,n=1),4,13)         # last one found is earliest
 sonicDate<-make_datetime(as.numeric(substr(s,1,4)),
		as.numeric(substr(s,6,7)),as.numeric(substr(s,9,10)))
# --------------------------------------- get elevations --------------------------------
 expr<-'elevationType'; s<-Seg(expr,120,homr)
 expr<-'GROUND'; s<-Seg(expr,120,s)
 expr<-'elevationMeters';  s<-Seg(expr,80,s)
 elevations<-as.numeric(numextract(substr(s,1,15)))
 dates<-Seg('beginDate\":\"',10,s)
 elevDates<-make_datetime(as.numeric(substr(dates,1,4)),
		as.numeric(substr(dates,6,7)),as.numeric(substr(dates,9,10)))
 # -------------------------------------- compile data list -------------------------------
 return(list(StnName=StnName,county=county,state=state,utcOffset=Hoffset,
   NCDC=NCDC,COOP=COOP,WBAN=WBAN,WMO=WMO,ICAO=ICAO,FAA=FAA,latitudes=latitudes,
   latDates=latDates,longitudes=longitudes,longDates=longDates,elevations=elevations,elevDates=elevDates,
   sonicDate=sonicDate))
}
