### ISSUE TITLE
Vignettes?

### ISSUE THREAD

**Issue by kjschaudt** [ropensci/rnoaa#389]
The documentation, such as https://docs.ropensci.org/rnoaa/, says that vignettes are available in the package.   Am unable to locate them using vignettes() in rnoaa 1.3.2.   Is that available in a development version?

**Comment by sckott** [comment]
thanks @kjschaudt for your question. Sorry about that. There are vignettes in the docs here https://docs.ropensci.org/rnoaa/ - linked from the pkg landing page https://cloud.r-project.org/web/packages/rnoaa/ 

I've been removing vignettes from the cran version because cran is checking vignettes for all kinds of things that hold up new version submissions

**Comment by kjschaudt** [comment]
Scott,

Perhaps, I am missing something.   I've checked 
https://docs.ropensci.org/rnoaa/ <https://docs.ropensci.org/rnoaa/> 
using both safari and firefox.  Vignettes are listed but there are no 
active links to any documents from that page.

The vignettes command does not reveal any vignettes in the version of 
rnoaa downloaded.   Would it be better to try a different source for rnoaa?

Thanks,

Ken

**Comment by sckott** [comment]
Did you try "Articles"?  

<img width="1035" alt="Screen Shot 2021-05-03 at 4 43 33 PM" src="https://user-images.githubusercontent.com/577668/116946345-bb8d3a00-ac2e-11eb-9aa1-e76f86a883a1.png">


And "Getting Started" is also a vignette

**Comment by kjschaudt** [comment]
AHA!  I didn't realize that the vignettes were filed under Articles.   I followed the link at HELP GETTING STARTED in the main body of the text and looked for a link in the bulleted list below that heading.    That will help next time I check rnoaa's capabilities.   Any thoughts on extending it to handle the International's Best Track Archive from the NCDC?   https://www.ncdc.noaa.gov/ibtracs/index.php?name=ib-v4-access

**Comment by sckott** [comment]
Are you asking for a IBTRACS vignette?

**Comment by kjschaudt** [comment]
The documentation on tropical storms seemed too say rnoaa only handles the data in the US databases, not the best track data in the IBTRACS format.   Was I mistaken?

**Comment by sckott** [comment]
We used to have access to IBTRACS in `rnoaa`, but I [removed it last summer](https://github.com/ropensci/rnoaa/commit/1bc28985819aa497ed78d611f37206c8cd72aa0f) as it was too unreliable

**Comment by kjschaudt** [comment]
Yep.   I turned to rnoaa hoping that a reliable solution might be found there.

**Comment by sckott** [comment]
you can use the code we had for IBTRACS if you want, its openly licensed https://github.com/ropensci/rnoaa/blob/v1.1.0/R/storms.R
