### ISSUE TITLE
Download data from rnoaa (error in API key)

### ISSUE THREAD

**Issue by SaraAV** [ropensci/rnoaa#390]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by SaraAV** [comment]
I am trying to download data from NOAA using the rnoaa package of R.

I am using ncdc_stations function to download some data:

siteNumber <- "GHCND:USC00023505"
metadata_station <- ncdc_stations(datasetid='GHCND', stationid=siteNumber)


However, I am getting the following error:

Error in check_response(ncdc_GET(path, args, token, ...)) : 
  x$response_headers$`content-type` == "application/json;charset=UTF-8" is not TRUE


Someone knows how to solve this issue?

**Comment by sckott** [comment]
thanks! having a look

**Comment by sckott** [comment]
@SaraAV Please try again after reinstalling like `remotes::install_github("ropensci/rnoaa")`

**Comment by fbdelac** [comment]
This has been driving me crazy. Thanks for the fix it worked.

**Comment by SaraAV** [comment]
Thanks sckott, it works!
