### ISSUE TITLE
DADA2 with Loop Genomics Long Read Issue

### ISSUE THREAD

**Issue by sgreimanbio** [ropensci/rnoaa#392]
We are running DADA2 following the PACBIO Fecal Sample example for loop genomics 16S data. We are at the learn error section but keep getting an error on the saveRDS command. Could you please help

> saveRDS(err1, file.path(path.rds, "Fecal_err1.rds"))
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'RDS//Fecal_err1.rds', probable reason 'No such file or directory'

**Comment by sckott** [comment]
wrong repo i assume?

**Comment by sgreimanbio** [comment]
Yes, sorry.
