### ISSUE TITLE
Issues after installing R 4.1.2

### ISSUE THREAD

**Issue by erinlarson** [ropensci/rnoaa#407]
After installing the latest version of R, I keep getting an error about the formatting of headers when trying to retrieve data. Seems to be an issue with the curl package?

Example:
`ncdc_stations(stationid='COOP:010008')`
Error in curl::handle_setheaders(opts$url$handle, .list = opts$headers) : 
  All headers must be strings.

**Comment by djhocking** [comment]
What version of R and what operating system? Did you install from CRAN or GitHub? This info will help me track down the bug if it's not in my current system.

**Comment by erinlarson** [comment]
I'm using R 4.1.2... but I also think I might have resolved the issue. I had a digit missing from my token, which might have been causing the error.

**Comment by djhocking** [comment]
Okay, great. I'm glad it seems to be working now. I'll close this issue but feel free to reopen it if it turns out to not be resolved.
