### ISSUE TITLE
Problem with lcd function in rnoaa package

### ISSUE THREAD

**Issue by drworms** [ropensci/rnoaa#409]
I'm a R noob. I am trying to fetch all lcd monthly data for a particular weather station. I am using the lcd function as shown in the example in the rnoaa documentation. I keep getting a 404 error. I've included a screenshot of my script for reference. Thanks for your help.

```
x = lcd(station = "US1FLSW0008", year = 2019)
lcd(station = "US1FLSW0008", year = 2019)
```
![lcd_problem](https://user-images.githubusercontent.com/54248044/168064816-dd2247f3-02a3-4f50-b463-863be175ba0a.JPG)

**Comment by PDXChris** [comment]
I'm having a similar issue, but with a different error message.  The command:
> lcd('72698024229', year = 2019)

produces the following error message, but only for year = 2019; all other years from 2010:2022 work:

Error in safe_read_csv(path, col_types = col_types) : 
  Attempt to override column 65 <<MonthlyGreatestSnowfall>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.

**Comment by djhocking** [comment]
Unfortunately, NOAA changed the API completely without notifying users/developers. These are two different issues but I'm not going to be able to fix either of them in the current rnoaa package. I am started rnoaa2 from scratch but I don't have a timeframe for when it will be available. I will add a startup message with this warning to the current rnoaa package. I'm really sorry for the inconvenience.
