### ISSUE TITLE
RCurl multi handle throwing error

### ISSUE THREAD

**Issue by amirkav** [ropensci/rnoaa#60]
Thanks for this very useful R Package!

When a R process is interrupted in the middle of an API call while a handle is open, the handle is not properly closed before the next API call, resulting in the following error:

Error in function (type, msg, asError = TRUE)  : 
  easy handled already used in multi handle

This is a known issue (https://github.com/hadley/httr/issues/112), but I think it can be fixed by closing all available handles before making a new API call so that existing handles do not throw errors. I had a similar issue in my code, and fixed it by using POST() from RCurl package:
cpr.resp <- POST(handle=handle(url=...))

HTH. 

Amir

**Comment by sckott** [comment]
this shouldn't be a problem now with the most recent `httr`

**Comment by whryan** [comment]
Hi,

I'm getting this error again. When I am using lapply to make a number of requests, and then stop the process before it is finished, it will throw this error whenever I try to use GET thereafter.

**Comment by sckott** [comment]
hi @whryan - what version of `rnoaa` and `httr` are you running

**Comment by StefioCeccon** [comment]
A (not great) workaround is also to detach the library and re-attaching it if that helps: 

detach("package:rCurl", unload=TRUE)
detach("package:httr", unload=TRUE)
library(rCurl)
library(httr)

**Comment by sckott** [comment]
Thanks @StefioCeccon - However, this shouldn't happen anymore because `rnoaa` requires a minimum `httr` version https://github.com/ropensci/rnoaa/blob/master/DESCRIPTION#L27 that has the fix
