### ISSUE TITLE
Request to add more sources from erddap from NOAA

### ISSUE THREAD

**Issue by emhart** [ropensci/rnoaa#63]
An e-mail I received this morning from NOAA.

tl;dr - add more data from http://upwell.pfeg.noaa.gov/erddap

> Hi:
>
> I noticed with interest that your R package rNOAA contains a function erddap.r, as one of our group, Bob Simons, developed ERDDAP.  I am writing because i notice you are have only implemented the tabledap part of the service, and only pointing at our (ERD) ERDDAP.  I strongly urge you in a next version to not only include the griddap part of ERDDAP, but to point to:
>
> http://upwell.pfeg.noaa.gov/erddap
>
> The UAF ERDDAP has almost 5500 datasets  (and here a datatset really means a dataset - files are virtually aggregated over time) and all of the gridded datasets are CF compliant.  I also strongly encourage you to support both the ERDDAP griddap interface as well as the OPeNDAP interface.  I think you will find that there are way more NOAA data available through these APIs then through the NCDC API.  OPeNDAP is also used in many other places besides NOAA, while the same can't be said of the NCDC API.
>
> Thanks for your consideration.
>
> -Roy M.
>
> **********************
> "The contents of this message do not reflect any position of the U.S. Government or NOAA."
> **********************
> Roy Mendelssohn
> Supervisory Operations Research Analyst
> NOAA/NMFS
> Environmental Research Division
> Southwest Fisheries Science Center

**Comment by sckott** [comment]
done, erddadp not in rnoaa anymore,
